name: wordle_turkish
description: Türkçe Wordle klonu

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  flutter_native_splash: ^2.4.1
  # Firebase paketleri
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/turkce_kelime_listesi.txt
    - assets/kelimeler.json
    - assets/ixel.mp4

flutter_native_splash:
  color: "#667eea"
  color_dark: "#764ba2"
  android_12:
    color: "#667eea"
    color_dark: "#764ba2"
  web: false